CREATE USER grafana_user WITH LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
ALTER USER grafana_user WITH PASSWORD 'grafana';
CREATE DATABASE grafana WITH OWNER = grafana_user ENCODING = 'UTF8' CONNECTION LIMIT = -1;

CREATE DATABASE argos;

CREATE USER argosadmin;
ALTER USER argosadmin with PASSWORD 'argosAdmin';

CREATE USER grafana;
ALTER USER grafana with PASSWORD 'grafanaUser';

CREATE USER nodered;
ALTER USER nodered with PASSWORD 'noderedUser';

\connect argos

CREATE TABLE IF NOT EXISTS CAT_SENSORES(
	CODIGO VARCHAR(20) PRIMARY KEY,
	ENDERECO VARCHAR(50) NULL,
	CIDADE VARCHAR(50) NULL,
	BAIRRO VARCHAR(50) NULL,
	LATITUDE NUMERIC,
	LONGITUDE NUMERIC	
);

CREATE TABLE IF NOT EXISTS  CAT_ESTADO_ORDEM(ESTADO VARCHAR(12) PRIMARY KEY );
INSERT INTO CAT_ESTADO_ORDEM VALUES('FINALIZADA');
INSERT INTO CAT_ESTADO_ORDEM VALUES('EM ANDAMENTO');


CREATE TABLE IF NOT EXISTS  SEVERIDADE (SEVERIDADE VARCHAR(7) PRIMARY KEY);
INSERT INTO SEVERIDADE VALUES('NULO');
INSERT INTO SEVERIDADE VALUES('BAIXO');
INSERT INTO SEVERIDADE VALUES('MEDIO');
INSERT INTO SEVERIDADE VALUES('ALTO');
INSERT INTO SEVERIDADE VALUES('CRITICO');

CREATE TABLE IF NOT EXISTS CAT_SEVERIDADE_VAZAMENTO(
	SEVERIDADE VARCHAR(7),
	VAZAMENTO NUMERIC ,
	PRIMARY KEY (VAZAMENTO),
	FOREIGN KEY (SEVERIDADE) REFERENCES SEVERIDADE(SEVERIDADE)
);

INSERT INTO CAT_SEVERIDADE_VAZAMENTO VALUES('NULO',0.005);
INSERT INTO CAT_SEVERIDADE_VAZAMENTO VALUES('BAIXO',0.02);
INSERT INTO CAT_SEVERIDADE_VAZAMENTO VALUES('MEDIO',0.04);
INSERT INTO CAT_SEVERIDADE_VAZAMENTO VALUES('ALTO',0.06);
INSERT INTO CAT_SEVERIDADE_VAZAMENTO VALUES('CRITICO',0.08);

CREATE TABLE IF NOT EXISTS ORDEM_SERVICO(
	ID SERIAL, 
	ESTADO VARCHAR (12) DEFAULT 'EM ANDAMENTO',
	VALOR MONEY DEFAULT 0,
	abastecimento_efetivo numeric DEFAULT 0, 
	VAZAMENTO numeric DEFAULT 0,
	SEVERIDADE_VAZAMENTO VARCHAR(7) DEFAULT 'NULO', 
	SENSOR VARCHAR(20) NOT NULL, 
	FOREIGN KEY(ESTADO) REFERENCES CAT_ESTADO_ORDEM (ESTADO),
	FOREIGN KEY(SEVERIDADE_VAZAMENTO) REFERENCES SEVERIDADE(SEVERIDADE),
	FOREIGN KEY(SENSOR) REFERENCES CAT_SENSORES(CODIGO),
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS  DADOS_COLETADO(
	ID_ordem INT,
	SENSOR VARCHAR(20),
	entrada_combustivel NUMERIC NOT NULL,
	saida_combustivel NUMERIC NOT NULL,
	diferenca NUMERIC NOT NULL,
	timestamp timestamp with time zone,
	FOREIGN KEY(ID_ordem) REFERENCES ORDEM_SERVICO (ID),
	FOREIGN KEY(SENSOR) REFERENCES CAT_SENSORES(CODIGO),
	primary key (SENSOR, TIMESTAMP)
);


INSERT INTO CAT_SENSORES(CODIGO, ENDERECO, CIDADE, BAIRRO)
VALUES ('argos' ,'não especificado','não especificado','não especificado');

GRANT ALL PRIVILEGES ON DATABASE argos TO argosAdmin;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO argosAdmin;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO grafana;

GRANT SELECT, INSERT, UPDATE  ON ALL TABLES IN SCHEMA public TO nodered;
GRANT USAGE, SELECT ON SEQUENCE ordem_servico_id_seq TO nodered;

create table LORA_DATA(
packetId numeric,
packetLegth numeric,
arrivedTime timestamp with time zone,
sendedTime timestamp with time zone primary key,
delay numeric,
fuel numeric, 
latitude numeric, 
longitude numeric
);
